$(document).ready(function(){
	$('.box').click(function(){
		$('.box').fadeOut(2000);
		$('.box').children('p').fadeOut(1000);
	});
	$('#radio-2').click(function(){
		$('.fml').fadeOut(3000);
	});
	$('#radio-2').siblings('input').click(function(){
		$('.fml').fadeIn(1000);
	});
});